### ISSUE TITLE
Can I combine VMSS custom image with multiple account storages?

### ISSUE THREAD

**Issue by rerime** [gbowerman/azure-myriad#23]
Hi, I want take golden vhd image and spread VMSS creation to multiple  storage accounts, is it possible?
I'm trying do it, but no success.
Template does not accept "vhdContainers" with custom image.

`{
      "type": "Microsoft.Compute/virtualMachineScaleSets",
      ...
        "virtualMachineProfile": {
          "storageProfile": {
            "osDisk": {
             ...
              "image": {
                "uri": "[parameters('imageSource')]"
              }`

**Comment by gbowerman** [comment]
Hi @rerime, not yet. VMSS support for custom image with multiple storage accounts is coming this year, but for now you're limited to a single storage account when you use a custom image.

**Comment by rerime** [comment]
Thanks.

**Comment by carlostur** [comment]
Hi,
Are there any news about when this option will be available?
Thanks.

**Comment by gbowerman** [comment]
Hi @carlostur managed disks are currently in preview, and this allows you to have more custom image VMs in a scale set. We expect this to be publically available in Q1 of this year.
