### ISSUE TITLE
Some demos are not working

### ISSUE THREAD

**Issue by camiloahm** [gbowerman/azure-myriad#24]
I looks that the image was removed.

{
  "error": {
    "code": "ImageNotFound",
    "target": "imageReference",
    "message": "The platform image 'Canonical:UbuntuServer:15.04:latest' is not available. Verify that all fields in the storage profile are correct."
  }
}

**Comment by gbowerman** [comment]
Thanks @camiloahm I'll go through and convert any Ubuntu 15.x references to 16.04. Please note that the templates in this repo include some historical ones which are not maintained. The best place for supported VMSS templates is the Azure Quickstart templates repo: https://github.com/Azure/azure-quickstart-templates

**Comment by gbowerman** [comment]
Updated Ubuntu references to 16.04.0-LTS/latest.
