### ISSUE TITLE
Error deploying autoscale\vmss-win-autoscale

### ISSUE THREAD

**Issue by FernandoMorais** [gbowerman/azure-myriad#25]
Hi,

I'm trying to deploy the template, but I still getting the error:

ERROR TYPE
Deployment template validation failed: 'The template variable 'storageApi' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'. (Code: InvalidTemplate)

I really need some help on solving this.

Thanks in advance!

**Comment by gbowerman** [comment]
@FernandoMorais thanks for reporting this. Fixed the references in this and 2 other files. See https://github.com/gbowerman/azure-myriad/commit/9fe2790cd64e4d0eaaa93f16b6f4fd3f2eaf04e9
Note: We are in the process of moving all autoscale templates to use host level metrics. This makes the templates easier to write and more readable, and makes autoscale more reliable. Look at the autoscale VMSS templates in Azure Quickstart templates for examples. I advise against any autoscale deployments which use diagnostics extensions unless you specifically need to scale on memory.
