### ISSUE TITLE
why vmss-linux-custionimage always chose the first subnet

### ISSUE THREAD

**Issue by xiaochao** [gbowerman/azure-myriad#26]
"variables": {
    "namingInfix": "[toLower(substring(concat(parameters('vmssName'), uniqueString(resourceGroup().id)), 0, 11))]",
    "longNamingInfix": "[toLower(parameters('vmssName'))]",
    "addressPrefix": "10.1.0.0/16",
    "subnetPrefix": "10.1.5.0/24",
    "virtualNetworkName": "mtbox-vnet",
    "publicIPAddressName": "[concat(variables('namingInfix'), 'pip')]",
    "subnetName": "mtupload01",
    "loadBalancerName": "[concat(variables('namingInfix'), 'lb')]",
    "publicIPAddressID": "[resourceId('Microsoft.Network/publicIPAddresses',variables('publicIPAddressName'))]",
    "lbID": "[resourceId('Microsoft.Network/loadBalancers',variables('loadBalancerName'))]",
    "natPoolName": "[concat(variables('namingInfix'), 'natpool')]",
    "bePoolName": "[concat(variables('namingInfix'), 'bepool')]",
    "natStartPort": 50000,
    "natEndPort": 50119,
    "natBackendPort": 22,
    "nicName": "[concat(variables('namingInfix'), 'nic')]",
    "ipConfigName": "[concat(variables('namingInfix'), 'ipconfig')]",
    "frontEndIPConfigID": "[concat(variables('lbID'),'/frontendIPConfigurations/loadBalancerFrontEnd')]",
    "computeApiVersion": "2016-03-30",
    "networkApiVersion": "2016-03-30"
  },

error output:
 Subnet mtsandbox01 is in use by

mtsandbox01  10.1.0.0/24  52  -

mtsandbox02 10.1.2.0/24 251

mtsandbox03  10.1.3.0/24  251

mtsandbox04  10.1.4.0/24  251

mtupload01  10.1.5.0/24   251

i chose mtupload01 subnet.But it is output error

**Comment by gbowerman** [comment]
I don't understand what you mean. The custom image template only defines one subnet.

**Comment by gbowerman** [comment]
A VM scale set will only use one custom image.
